apiVersion: v2
name: kestra

description: Infinitely scalable, event-driven, language-agnostic orchestration and scheduling platform to manage millions of workflows declaratively in code.
home: https://kestra.io
version: 0.17.0
appVersion: "0.17.0"
keywords:
  - orchestrator
  - scheduler
  - workflow
icon: https://kestra.io/favicon-192x192.png
sources:
  - https://github.com/kestra-io/helm-charts
maintainers:
  - name: tchiotludo
    email: tchiot.ludo@gmail.com

type: application

annotations:
  artifacthub.io/links: |
    - name: Documentation
      url: https://kestra.io/docs/
  artifacthub.io/screenshots: |
    - title: Home page
      url: https://raw.githubusercontent.com/kestra-io/kestra.io/main/public/docs/user-interface-guide/02-Homepage-Empty.png
    - title: Flows list
      url: https://raw.githubusercontent.com/kestra-io/kestra.io/main/public/docs/user-interface-guide/04-Flows.png
    - title: Flow page
      url: https://raw.githubusercontent.com/kestra-io/kestra.io/main/public/docs/user-interface-guide/05-Flows-Flow.png
    - title: Execution list
      url: https://raw.githubusercontent.com/kestra-io/kestra.io/main/public/docs/user-interface-guide/08-Executions.png
    - title: Execution page
      url: https://raw.githubusercontent.com/kestra-io/kestra.io/main/public/docs/user-interface-guide/09-Executions-Execution.png
    - title: Execution gantt
      url: https://raw.githubusercontent.com/kestra-io/kestra.io/main/public/docs/user-interface-guide/27-Executions-Gantt.png
    - title: Namespaces list
      url: https://raw.githubusercontent.com/kestra-io/kestra.io/main/public/docs/user-interface-guide/14-EE-Namespace.png
    - title: Global logs
      url: https://raw.githubusercontent.com/kestra-io/kestra.io/main/public/docs/user-interface-guide/10-Logs.png
    - title: Documentation
      url: https://raw.githubusercontent.com/kestra-io/kestra.io/main/public/docs/user-interface-guide/12-Documentations-Plugins-Plugin.png

dependencies:
  - name: elasticsearch
    version: ^7.17.3
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: kafka
    version: ^18.3.1
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: minio
    version: ^4.0.13
    repository: https://charts.min.io/
    condition: minio.enabled
  - name: postgresql
    condition: postgresql.enabled
    repository: https://charts.bitnami.com/bitnami
    version: "~12.2.2"
